otel:
  otel.exporter.otlp.metrics.protocol: noop
patchDirectory: src/main/connector
resources:
  anyHost:
    attributes:
      host.name: anyHost
      host.type: windows
    protocols:
      emulation:
        wmi:
          directory: src/it/resources/WindowsIpmiTool/emulation/wmi
    connectors: [ +WindowsIpmiTool ]