#MetricsHub Configuration
patchDirectory: "src/main/connector"
resources:
  localhost:
    attributes:
      host.name: localhost
      host.type: linux
    protocols:
      jdbc:
        timeout: 300
        type: mysql
    connectors: ["+MySql"]