#MetricsHub Configuration
patchDirectory: "src/main/connector"
resources:
  localhost:
    attributes:
      host.name: localhost
      host.type: linux
    protocols:
      snmp:
        timeout: 300
    connectors: ["+SmartMonLinux"]