#MetricsHub Configuration
patchDirectory: "src/main/connector"
resources:
  localhost:
    attributes:
      host.name: localhost
      host.type: windows
    protocols:
      wmi:
        timeout: 300
    connectors: ["+WbemGenDiskNT"]