#MetricsHub Configuration
patchDirectory: "src/main/connector"
resources:
  localhost:
    attributes:
      host.name: localhost
      host.type: linux
    protocols:
      ssh:
        username: user
        password: password
        timeout: 300
    connectors: ["+Linux"]