#MetricsHub Configuration
otel:
  otel.exporter.otlp.metrics.protocol: noop
patchDirectory: "src/main/connector"
resources:
  anyhost:
    attributes:
      host.name: anyhost
      host.type: oob
    protocols:
      emulation:
        http:
          directory: src/it/resources/Redfish/emulation/http
    connectors: [ +Redfish ]