otel:
  otel.exporter.otlp.metrics.protocol: noop
patchDirectory: "src/main/connector"
resources:
  anyHost:
    attributes:
      host.name: anyHost
      host.type: linux
    protocols:
      emulation:
        ssh:
          directory: src/it/resources/LinuxIpmiTool/emulation/command
    connectors: ["+LinuxIpmiTool"]